name: Test pypiserver chart

on:
  pull_request:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install requirements
        run: sudo bash $(pwd)/scripts/requirements.sh

      - name: Template chart with default values
        run: helm template pypiserver/ --debug

      - name: Template chart with example values
        run: for i in example/*.yaml ; do helm template -f "$i" pypiserver/ --debug ; done

      - name: Lint chart
        run: helm lint pypiserver/